/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsAskyourpagesRouteImport } from './routes/projects/askyourpages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAskyourpagesRoute = ProjectsAskyourpagesRouteImport.update({
  id: '/projects/askyourpages',
  path: '/projects/askyourpages',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/askyourpages': typeof ProjectsAskyourpagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/askyourpages': typeof ProjectsAskyourpagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/askyourpages': typeof ProjectsAskyourpagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/askyourpages'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/askyourpages'
  id: '__root__' | '/' | '/projects/askyourpages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsAskyourpagesRoute: typeof ProjectsAskyourpagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/askyourpages': {
      id: '/projects/askyourpages'
      path: '/projects/askyourpages'
      fullPath: '/projects/askyourpages'
      preLoaderRoute: typeof ProjectsAskyourpagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsAskyourpagesRoute: ProjectsAskyourpagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
